### ISSUE TITLE
Custom fontello

### ISSUE THREAD

**Issue by MrC8** [micc83/acf-fonticonpicker#12] opened 2017-09-18 15:22 UTC
Hi,
Well done for this plugin !
I don't understand, but if I replace your icons folder by my own custom fontello folder, your plugin says "No icons found"... I don't understand why... I compared yours config.json and mine and I dont found what is wrong... Can you help me ? I just want to load my own fonts...

**Comment by micc83** [comment] 2017-09-19 07:00
https://github.com/micc83/acf-fonticonpicker/blob/6cee4e16cdc6213bb36f0a2a210a89407d3a2bae/fonticonpicker-v5.php#L67-L70

Hi, the error "No icons found" means that the file hasn't been found or it's invalid json. You can remove the `@` from the code below to debug your issue:

https://github.com/micc83/acf-fonticonpicker/blob/6cee4e16cdc6213bb36f0a2a210a89407d3a2bae/fonticonpicker-v5.php#L40-L43

**Comment by MrC8** [comment] 2017-09-19 07:44
Hi,
I tried to reupload your plugin without my modification and I still have the message "No icons found", even with your default plugin...
I tried your solution and actived the debug and I get : 
Warning: file_get_contents(https://www.website.com/wp-content/plugins/acf-fonticonpicker/icons/config.json): failed to open stream: HTTP request failed! HTTP/1.1 401 Authorization Required in /home/clients/99e7aa2d711ad8e28c4438d1d9c3c53f/website/wp-content/plugins/acf-fonticonpicker/fonticonpicker-v5.php on line 41

**Comment by DecoGrafics** [comment] 2018-05-18 07:25
I am having the same issue. Any fix for this?

**Comment by micc83** [comment] 2018-05-18 08:48
If the issue is the same of @MrC8:
```
Warning: file_get_contents(https://www.website.com/wp-content/plugins/acf-fonticonpicker/icons/config.json): failed to open stream
```
Then there's probably some issue in the path where you installed the plugin. The file `config.json` should be indeed located at:
```
/wp-content/plugins/acf-fonticonpicker/icons/config.json
```

**Comment by micc83** [comment] 2018-05-18 08:50
Also, if you're on https, check the following:
https://stackoverflow.com/questions/1975461/how-to-get-file-get-contents-to-work-with-https

**Closed as completed** 2022-06-13 07:25 UTC
